### ISSUE TITLE
Upload version to PyPI

### ISSUE THREAD

**Issue by Gr1N** [nats-io/asyncio-nats#21]
Hi!

It's me again. :)
Could you please upload new version of package to PyPI with this helpful fix https://github.com/nats-io/asyncio-nats/commit/4888b43b218d583990b4597bcbea0fd635bd9988?

**Comment by wallyqs** [comment]
Done! please confirm :)
Fixed via #22

**Comment by Gr1N** [comment]
Great! Many thanks!
