### ISSUE TITLE
Support nats streaming server

### ISSUE THREAD

**Issue by mackeyja92** [nats-io/asyncio-nats#23]
Does this library support nats streaming server?

**Comment by wallyqs** [comment]
Not currently, but planning to support eventually with another library which uses this as a dependency

**Comment by mackeyja92** [comment]
That's too bad! I was really looking at nats for the streaming server pieces. Do you have a timeline?

**Comment by mackeyja92** [comment]
See http://github.com/mackeyja92/asyncio-nats-streaming
