### ISSUE TITLE
v0.3.3 release ?

### ISSUE THREAD

**Issue by sam3000** [nats-io/asyncio-nats#26]
Hi,

I was wondering if something is blocking the v0.3.3 release or are we just missing the tag ?

Thanks

**Comment by wallyqs** [comment]
Hi, only bumped the version in the repo but haven't pushed or tagged a release yet with it.

**Comment by wallyqs** [comment]
Thanks for the wait v0.4.0 is on pypi now: https://github.com/nats-io/asyncio-nats/releases/tag/v0.4.0
