### ISSUE TITLE
Auth Code Authentication

### ISSUE THREAD

**Issue by mfdeux** [nats-io/asyncio-nats#37]
Will auth code authentication be included? Authenticating with token in connection string (i.e. "nats://TOKEN@localhost:4222") passes in the token as username server side.  Changing to "nats://:TOKEN@localhost:4222" passes the token in as password, but still does not work.

**Comment by wallyqs** [comment]
Sorry, looks like it is missing so need to add it... https://github.com/nats-io/asyncio-nats/blob/master/nats/aio/client.py#L684-L695
You're right that it should be picking up the token from the passed username and sending `auth_token` as part of the `CONNECT` payload.

**Comment by shiundu** [comment]
@wallyqs  Ah, you were already on it.

**Comment by shiundu** [comment]
Thanks, works like a charm!
