### ISSUE TITLE
Is buffer / max payload size is fixed?

### ISSUE THREAD

**Issue by djKooks** [nats-io/asyncio-nats#46]
Hello~
I'm bit experienced in `rabbitmq`, but almost newbie in nats. 
While looking on project, it seems max_payload and buffer size are set as default and unchangeable outside of module. Is this the correct part?

Thanks.

**Comment by tylertreat** [comment]
`max_payload` defaults to 1MB, but it can be configured in the server: http://nats.io/documentation/server/gnatsd-config/

**Comment by djKooks** [comment]
@tylertreat Oh thanks! In this case, do I need to fix max payload value in client, too?

**Comment by wallyqs** [comment]
Hi @djKooks it wouldn't be needed to tweak the max payload value in the client since the server announces what would be the maximum payload size to the client when it connects via the `INFO` command.

**Comment by djKooks** [comment]
@wallyqs Thanks for answer! I get it now.
