### ISSUE TITLE
How it works with service on Golang with gob encoder

### ISSUE THREAD

**Issue by morozovcookie** [nats-io/asyncio-nats#51]
Hello! I have two service: first on Python and second on Golang. On the second service I use NATS with gob encoder. So could there be any problems? Or all work fine "from box"?
Thank you.

**Comment by wallyqs** [comment]
The python client does not have encoders/decoders functionality like the Go client does so the python application would have to do the unmarshalling of the payload via some library. The NATS Streaming client uses protocol buffers for example https://github.com/nats-io/asyncio-nats-streaming/blob/6894ec2a9c8dfc19241f0a5c0b6b730c75b1a306/stan/aio/client.py#L132-L147
