### ISSUE TITLE
This is unfortunatly completly useless without even the most basic examples

### ISSUE THREAD

**Issue by tpihl** [nats-io/asyncio-nats#60]
I was hopeful when i saw CloudNative but this doc is horrible and seems to be moved forward forever. Go side is useful, but this.....

Not a single example where the nats server is somewhere except on localhost. I really doubt NATS is valuable in the community at this stage and maybe we should select more community-friendly cloud-native tools.

And not a single example or ambition to support non-asyncio-approach. Most python scripts are small and become over-complex if they need asyncio mandatory for simple devops stuff or similar. 

To bad.
/T

**Comment by wallyqs** [comment]
Thanks for the feedback, sorry to hear that you find asyncio complex to use, I think using coroutines is a great approach for Python. In the readme there are some examples of how to connect to a different server but I will make another pass to the docs.  Have thought on making a threaded version of the client but no plans right now, feedback here helps a lot!

**Comment by wallyqs** [comment]
Made some updates to the examples to find how to connect to a non localhost more easily,  thanks for the feedback on the non-asyncio-approach 👍
