### ISSUE TITLE
functools.partial as callback on request

### ISSUE THREAD

**Issue by aratz-lasa** [nats-io/asyncio-nats#97]
I think it would be a nice idea if you could pass an async function wrapped on functools.partial.
It would be just to add two lines in nats-->aio-->client.py-->line 509:
`elif hasattr(cb, "func") and asyncio.iscoroutinefunction(cb.func):
                sub.coro = cb`

**Comment by wallyqs** [comment]
this sounds good to me, feel free to send PR :)

**Comment by aratz-lasa** [comment]
Okay thanks for the quick response!
